name: gr
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=1.4.0
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=23.1.0
  - blas=1.0
  - blinker=1.6.2
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cachetools=5.3.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.0.0
  - colorama=0.4.6
  - contourpy=1.1.1
  - cryptography=38.0.4
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=10.1.243
  - cycler=0.11.0
  - cyrus-sasl=2.1.27
  - cytoolz=0.12.0
  - dask-core=2022.2.1
  - dataclasses=0.8
  - dbus=1.13.18
  - einops=0.6.1
  - expat=2.5.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - flatbuffers=23.5.26
  - fontconfig=2.14.1
  - fonttools=4.43.0
  - freetype=2.12.1
  - freetype-py=2.4.0
  - frozenlist=1.3.3
  - fsspec=2022.2.0
  - future=0.18.3
  - gast=0.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-auth=2.22.0
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.9.0
  - hdf5=1.12.1
  - icu=58.2
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - importlib-metadata=6.8.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - jxrlib=1.1
  - keras=2.12.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.2.10
  - libcups=2.4.2
  - libcurand=10.3.3.141
  - libcurl=8.2.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libnpp=11.8.0.86
  - libntlm=1.4
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=13.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.16
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.4.4
  - markupsafe=2.1.1
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.23.5
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=21.3
  - partd=1.2.0
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.2.1
  - ply=3.11
  - plyfile=1.0.1
  - protobuf=3.20.3
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyglet=1.5.27
  - pyjwt=2.8.0
  - pyopengl=3.1.6
  - pyopenssl=23.2.0
  - pyparsing=3.0.4
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrender=0.1.45
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-flatbuffers=23.5.26
  - python_abi=3.11
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scikit-image=0.20.0
  - scipy=1.11.1
  - setuptools=68.0.0
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.12.0
  - tensorflow-base=2.12.0
  - tensorflow-estimator=2.12.0
  - termcolor=2.3.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.11.2
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.3.3
  - tqdm=4.66.1
  - trimesh=3.23.5
  - typing_extensions=4.7.1
  - urllib3=1.26.16
  - werkzeug=2.3.7
  - wheel=0.38.4
  - wrapt=1.15.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zfp=0.5.5
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - chamferdist==1.0.1
    - marching-cubes-cpp==0.0.0
    - pandas==2.1.0
    - pytorch-fid==0.3.0
    - pytz==2023.3.post1
    - tzdata==2023.3
